### ISSUE TITLE
about fragment_database_file

### ISSUE THREAD

**Issue by SvenColorLight** [UAMCAntwerpen/LEADD#7]
Following your tutorial, I built the environment through leadd_conda_env.yml，generate fragment.db fragment.cqr and other files,when i run the leadd_example.py,cannot found fragment_database_file through reconstructionSettings,have any method resolved this problem?

this is error message:

(LEADDtest) huqiao@user01-PR4904P:~/expriment/LEADD/example$ python leadd_example.py
Traceback (most recent call last):
  File "/home/huqiao/expriment/LEADD/example/leadd_example.py", line 97, in <module>
    Main()
  File "/home/huqiao/expriment/LEADD/example/leadd_example.py", line 47, in Main
    settings = pyLEADD.ReconstructionSettings('reconstruction_settings.txt')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ERROR: FRAGMENT_DATABASE_FILE doesn't reference an existing file.

this is reconstructionSettings.txt:

### Input file settings ###
FRAGMENT_DATABASE_FILE /home/huqiao/expriment/LEADD/example/fragment.db
CONNECTION_QUERY_RESULTS_FILE /home/huqiao/expriment/LEADD/example/fragment.cqr

thanks for your reply

**Comment by SvenColorLight** [comment]
already resolved, finally  understand the different between txt files about CRLF and LF under windows and linux
